// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://psvvyjhkqdmkwwcfzntj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdnZ5amhrcWRta3d3Y2Z6bnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NzAzNDUsImV4cCI6MjA1ODM0NjM0NX0.QHvC2fSiMZ9otuWJbr1m2Lo-K_eblCJqRGv4YMWQK2o";

// Import the supabase client like this:
// import { supabase } from "~/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
